[package]
name = "retris"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.24.0"
env_logger = "0.11.8"
kira = "0.11.0"
log = "0.4.29"
pollster = "0.4.0"
raw-window-handle = "0.6.2"
sdl2 = { version = "0.38.0", features = ["raw-window-handle", "bundled"] }
taffy = "0.9.2"
wgpu = "28.0.0"
